### ISSUE TITLE
Change message when zooming in beyond maxscale

### ISSUE THREAD

**Issue by bsimyo** [NICTA/nationalmap#102]
The message currently says:
 ---
The "Layer Name" dataset will not be shown when zoomed in this close to the map because the data custodian has deemed it to be too inaccurate to show at this scale...
 ---
Change to:
 ---
The "Layer Name" dataset will not be shown when zoomed in this close to the map because the data custodian has indicated that the data is not intended or suitable for display at this scale. ..
 ---

**Comment by kring** [comment]
This was done awhile ago.
