### ISSUE TITLE
WMS layers from data.gov.au missing

### ISSUE THREAD

**Issue by stevage** [NICTA/nationalmap#109]
Just noticed this layer doesn't appear:

https://data.gov.au/dataset/glenorchy-city-council-water-lines

The WMS layer within works just fine.

**Comment by kring** [comment]
It doesn't show up because NM can't deduce the layer name to use.  This section of the Data Provider's Guide explains the requirements:
https://github.com/NICTA/nationalmap/wiki/Data-Providers-Guide#web-map-service-wms

**Comment by kring** [comment]
Here's the relevant line:

> If the wms_layer property does not exist, and the layer cannot be deduced from the URL, the resource will not appear in the catalogue at all.

**Comment by stevage** [comment]
Ok, thanks.
