### ISSUE TITLE
Add disclaimer to NM UI

### ISSUE THREAD

**Issue by bsimyo** [NICTA/nationalmap#11]
See separate details in doc from Dept of Comms

**Comment by stevage** [comment]
The text:

>The NationalMap must not be used for navigation or precise spatial analysis

There doesn't seem to be any guidance about where this should go other than "On the map"

So where should we put it? @philipgrimmett @hilarycinis ?

* Squidged in with the tiny white text at the bottom? 
* Dark grey and semi transparent
* In the bottom of the data catalogue?

**Comment by hilarycinis** [comment]
Squidged in with the tiny white text at the bottom, along with the legals, thanks.

**Comment by hilarycinis** [comment]
![disclaimer](https://cloud.githubusercontent.com/assets/6046521/7643814/37479fca-fae0-11e4-9ec2-631d4498ef8b.png)
