### ISSUE TITLE
Nationalmap doesn't build with process in wiki

### ISSUE THREAD

**Issue by buggeru** [NICTA/nationalmap#113]
Hi guys,
I follwed the instructions on the wiki. However, when I run
 npm install
I get:

npm WARN unmet dependency /home/buggeru/nationalmap/node_modules/gulp-jsdoc requires gulp-util@'~2.2.14' but will load
npm WARN unmet dependency /home/buggeru/nationalmap/node_modules/gulp-util,
npm WARN unmet dependency which is version 3.0.6

Running gulp gives
Error: Cannot find module 'through2'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /home/buggeru/nationalmap/node_modules/gulp-jsdoc/index.js:4:18
    at Object.<anonymous> (/home/buggeru/nationalmap/node_modules/gulp-jsdoc/index.js:141:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

For reference uname -a 

Linux terminus 3.19.0-28-generic #30-Ubuntu SMP Mon Aug 31 15:52:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Help please!
Cheers,
B

**Comment by kring** [comment]
Did you run `npm install -g gulp` recently?  If not, `gulp` is probably referring to some old, possibly broken version of gulp from a previous endeavor.  Either run `npm install -g gulp` or run the local version explicitly with `./node_modules/.bin/gulp` and see if that helps.

**Comment by buggeru** [comment]
Hi and thanks.
I've tried your suggestions but the result is the same.

The install of the dev tools is brand new.

Any other suggestions welcome!

Cheers
B

**Comment by kring** [comment]
Did you get any other errors from `npm install`?  I just did this and it worked fine for me (also on Ubuntu):

```
git clone git@github.com:NICTA/nationalmap.git nm2
cd nm2
npm install
gulp
```

**Comment by buggeru** [comment]
Only as reported above:

npm WARN unmet dependency /home/buggeru/nationalmap/node_modules/gulp-jsdoc requires gulp-util@'~2.2.14' but will load
npm WARN unmet dependency /home/buggeru/nationalmap/node_modules/gulp-util,
npm WARN unmet dependency which is version 3.0.6

I'm actually using kubuntu but I doubt if that would make much of a difference.

**Comment by kring** [comment]
I wouldn't think it would.  Can you do a clean clone / npm install / gulp from scratch and send the entire output my way?  My email address is on the web site linked from my github profile.

**Comment by buggeru** [comment]
Success! I deleted everything and started again.
Maybe the phase of the moon was wrong the first time.

Thanks for your help.

**Comment by kring** [comment]
Glad to hear you got it working!
