### ISSUE TITLE
ABS Data Services timing out on first open

### ISSUE THREAD

**Issue by stevage** [NICTA/nationalmap#115]
While testing [this](https://github.com/TerriaJS/terriajs/pull/947) I noticed that many ABS Data Services layers time out when they're first loaded, but quickly load on second attempt. I don't know if this is something we can fix - or maybe we can just extend the timeout.

**Comment by kring** [comment]
@stevage I haven't seen this.  I don't think we're setting a timeout, so the browser should happily wait minutes or more for a response.  Do you know where the timeout was occurring?

**Comment by stevage** [comment]
Maybe they were doing maintenance or something. It's fine now.
