### ISSUE TITLE
Add disclaimer to NM printouts

### ISSUE THREAD

**Issue by bsimyo** [NICTA/nationalmap#12]
See separate doc from Dept of Comms

**Comment by stevage** [comment]
Where are the printouts kept? Presumably this is not required by Friday?

**Comment by bsimyo** [comment]
This refers to the printouts generated by browsers using the browsers' "print" command.

**Comment by stevage** [comment]
Here's the text required:

>The Department, NICTA and Geoscience Australia (“We”) make no representations or warranties regarding the accuracy or completeness of any content or the product in connection with the  NationalMap. We disclaim all responsibility and all liability (including without limitation, liability in  negligence, for errors or omissions) for all expenses, loss, damage and costs which you might incur  as a result of the information displayed on the NationalMap and your use of it.  The NationalMap must not be used for navigation or precise spatial analysis.
