### ISSUE TITLE
AREMI NationalMap has complex Share URL

### ISSUE THREAD

**Issue by indexgeo** [NICTA/nationalmap#124]
Using the "Share" feature of the main NationalMap provides a very concise URL, and this works beautifully. Also that is fine for the Northern Australia NationalMap.

However the AREMI NationalMap gives a very long and complex URL that would be prone to breaking, and could not be reliably shared.

**Comment by meh9** [comment]
Hi @indexgeo 

Note that AREMI has its own GitHub repo here: https://github.com/NICTA/aremi-natmap

We have been holding off switching to the shortened URL's while we try to figure out a way to fix this issue: https://github.com/TerriaJS/terriajs/issues/986

**Comment by kring** [comment]
@meh9 that may not be a very good reason to hold off.  With the shortening, we get a catalog of everything that has been shared and can potentially find a way to make it still work even after a layer is renamed.  Without the shortening, we have no idea.

**Comment by meh9** [comment]
@kring yeah, that is a good point. I was just hoping to have been able to think more about this by now and come up with a way forward but I've not had time.

**Comment by kring** [comment]
Closing this because it's for a different project and (at least so far) an intentional choice.

**Comment by meh9** [comment]
Sorry, forgot about this issue. We have now turned on the Google URL Shortener for AREMI, and this should go live in about a week.
