### ISSUE TITLE
Possible UI issue on mobile devices

### ISSUE THREAD

**Issue by dbutrovski** [NICTA/nationalmap#1256]
When user click on the search tool (upper-right corner magnifying glass icon), a gray box takes over upper part of the screen (please see attached screen grabs) but unable to enter any text or recover back to previous UI state. It requires browser refresh to recover.

iPhone X / iOS 16.7.2 / Safari

![nm_mobile_issue_1](https://github.com/TerriaJS/nationalmap/assets/13044371/81081539-6318-46c6-b9fc-8d702b623c03)

![nm_mobile_issue_2](https://github.com/TerriaJS/nationalmap/assets/13044371/349b3e04-662d-46af-a472-af65edde5f6e)

**Comment by nf-s** [comment]
Thanks for reporting this bug @dbutrovski - we will target this for the next release after the NY

**Comment by mwu2018** [comment]
Pending on terriajs v8.4.2 release.
