### ISSUE TITLE
Replace ABS boundaries (deprecate NationalMap GeoServer)

### ISSUE THREAD

**Issue by nf-s** [NICTA/nationalmap#1258]
We have some ABS boundaries in our GeoServer

- https://github.com/TerriaJS/saas-catalogs-public/blob/main/nationalmap/catalog/boundaries/prod.json

These can be replaced with either

- ArcGis REST services provided by ABS- https://www.abs.gov.au/statistics/standards/australian-statistical-geography-standard-asgs-edition-3/jul2021-jun2026/access-and-downloads/data-services-and-apis
- Region mapping vector tiles provided by us - https://github.com/TerriaJS/terriajs/blob/main/wwwroot/data/regionMapping.json

**Comment by sixlighthouses** [comment]
Current prod has an individual Mesh Block layer for each state and territory.  Swapped to using a national MB layer as supplied by ABS

**Comment by sixlighthouses** [comment]
Replaced nicta geoserver layers to the ABS Mapserver equivalents
CED 2011
CED 2016
Local Government Areas (2011)
State Suburbs
States & Territories
Australian Drainage Divisions
Natural Resource Management Regions
Tourism Regions
Australia Mesh Blocks

**Comment by sixlighthouses** [comment]
https://github.com/TerriaJS/saas-catalogs-public/pull/419

In production now
