### ISSUE TITLE
Replace GA "Lakes" and "Reservoirs" layers (deprecate NationalMap GeoServer)

### ISSUE THREAD

**Issue by nf-s** [NICTA/nationalmap#1259]
Replace the following layers

- https://nationalmap.gov.au/#share=s-McC6EkkIjycmcInPEZGQqLbW3d
- https://github.com/TerriaJS/saas-catalogs-public//blob/2801d1dc9193a6d63c582631556af064bd24e30b/nationalmap/catalog/energy/prod.json#L9923-L9949
- https://github.com/TerriaJS/saas-catalogs-public//blob/2801d1dc9193a6d63c582631556af064bd24e30b/nationalmap/catalog/energy/prod.json#L9880-L9906

There should be GA ArcGis MapServer layers available for these somewhere

**Comment by sixlighthouses** [comment]
https://github.com/TerriaJS/saas-catalogs-public/pull/419

In production now
