### ISSUE TITLE
Add minerals/resources datasources from AuScope

### ISSUE THREAD

**Issue by stevage** [NICTA/nationalmap#126]
AuScope has various data sources which perhaps should be added, eg:

http://www.mrt.tas.gov.au:80/web-services/wfs
http://geossdi.dmp.wa.gov.au:80/services/wfs
http://geology.data.nt.gov.au:80/geoserver/wfs
http://geology.data.vic.gov.au/nvcl/wfs

The NT one at least is a bit fragile, and fails if GeoJSON is requested for either WMS or WFS.

**Comment by RacingTadpole** [comment]
Not having much luck getting any of these to work. They can be added to the map (minus the :80 port numbers), but the data items load take forever to load, eventually giving a message such as "java.lang.ClassCastException: org.geotools.feature.FeatureImpl cannot be cast to org.opengis.feature.simple.SimpleFeature
org.geotools.feature.FeatureImpl cannot be cast to org.opengis.feature.simple.SimpleFeature".

I found some alternative URLs that look to have similar data at http://www.geoscience.gov.au/wms.html, but they have similar problems.
