### ISSUE TITLE
Data error in the NSW EV charge locations dataset reported

### ISSUE THREAD

**Issue by dbutrovski** [NICTA/nationalmap#1263]
Amy Maher from the Transport for NSW Future Mobility Team runs their electric vehicle website and they reference embedded NationalMap on the website homepage.

[https://www.transport.nsw.gov.au/projects/electric-vehicles/charging-an-electric-vehicle/nsw-electric-vehicle-charging-map]

[https://nationalmap.gov.au/#share=s-tTL9I3QezTdOcNIs96C61Ze5GZB]
 
Amy reported that a community member reached out and has let them know the Soldiers Point charger information is incorrect. The national map says it’s an AC 22 kW Tesla charger but it should be a 24 kW DC Chargefox charger. 
 Amy is interested in the process to reporting map issues and to fix the data issue.

It appears it is a dataset hosted on behalf of another entity and it still has references to decommissioned AREMI. From the About Data: "The data is supplied by the Electric Vehicle Council. Data is processed and by the Institute of Sustainable Futures at the University of Technology Sydney (UTS) for display on AREMI." 
Is this dataset still maintained?
In yes, should I just refer Amy to the EVC? Who is the contact?

Contact details:
Amy Maher 
Project and Communications Officer
Customer Strategy and Technology  
Transport for NSW  
Email amy.maher@transport.nsw.gov.au

**Comment by AnaBelgun** [comment]
EV data group updated in response to the report
