### ISSUE TITLE
National Map transport datasets

### ISSUE THREAD

**Issue by ljowen** [NICTA/nationalmap#1265]
Adding Transport > Roads via the catalog results in the dataset never loading, however adding manually or via sharelink works fine.

See https://nationalmap.gov.au/#share=s-yN0K0Sl1lLVmEW9CijspmMpy0rA

**Comment by mwu2018** [comment]
I've found that the datasets are loaded extremely slowly, taking about 1.5 min per dataset. Probably should ask if GA has throttled our proxy requests.
