### ISSUE TITLE
National Map - Update ABARES dataset urls

### ISSUE THREAD

**Issue by ljowen** [NICTA/nationalmap#1266]
jasmine howorth

 
ABARES have several datasets featured in the Data Catalogue for National Map under the Agriculture topic group.
The urls for these web services are changing and will no longer work from this Friday  21 June. The new URL prefix for all these layers is https://gis.environment.gov.au/gispubmap/rest/services/abares
 
The 2018 and 2020 layers which are currently on National Map and new URLs are listed below:
**Agriculture**
Catchment scale land use
- Catchment Scale Land Use 2020 - Primary classification https://gis.environment.gov.au/gispubmap/rest/services/abares/CLUM_50m/MapServer/0

- Catchment Scale Land Use 2020 - Secondary classification https://gis.environment.gov.au/gispubmap/rest/services/abares/CLUM_50m/MapServer/1

- Catchment Scale Land Use 2020 - 18 class classification https://gis.environment.gov.au/gispubmap/rest/services/abares/CLUM_50m/MapServer/2

- Catchment Scale Land Use 2020 – Agriculture https://gis.environment.gov.au/gispubmap/rest/services/abares/CLUM_50m/MapServer/3

- Catchment Scale Land Use 2020 - Agricultural industries https://gis.environment.gov.au/gispubmap/rest/services/abares/CLUM_50m/MapServer/4

- Catchment Scale Land Use 2020 - Date of mapping https://gis.environment.gov.au/gispubmap/rest/services/abares/CLUM_50m/MapServer/5

- Catchment Scale Land Use 2020 - Scale of mapping https://gis.environment.gov.au/gispubmap/rest/services/abares/CLUM_50m/MapServer/6

Forest web services
- Fire in Australia’s Forests (Number of fires 2011-12 to 2015-16) https://gis.environment.gov.au/gispubmap/rest/services/abares/AustStateOfForests2018/MapServer/1

- Fires in Australias Forests (Fire Type 2011-12 to 2015-16) https://gis.environment.gov.au/gispubmap/rest/services/abares/AustStateOfForests2018/MapServer/2

- Forests of Australia (2018)  https://gis.environment.gov.au/gispubmap/rest/services/abares/AustStateOfForests2018/MapServer/4

- Tenure of Australia's forests (2018) https://gis.environment.gov.au/gispubmap/rest/services/abares/AustStateOfForests2018/MapServer/0

**Comment by mwu2018** [comment]
"The new URL prefix for all these layers is https://gis.environment.gov.au/gispubmap/rest/services/abares" -- This seems incorrect because it is the same as what we already have in the current catalog. 

Besides, requests to https://gis.environment.gov.au/gispubmap/rest/services/abares will get "Bad Gateway" response. Is the server down?

**Comment by ljowen** [comment]
https://www.environment.gov.au/mapping/rest/services/abares/CLUM_50m/MapServer is what I'm seeing in prod, it looks like a redirect has been setup to `gis.environment.gov.au`

**Comment by ljowen** [comment]
Discovered url change needed for the Environment group also: 

```
"http://www.environment.gov.au/mapping/services/ogc_services/World_Heritage_Areas/MapServer/WMSServer",
"http://www.environment.gov.au/mapping/services/ogc_services/Commonwealth_Heritage_List/MapServer/WMSServer",
"http://www.environment.gov.au/mapping/services/ogc_services/Commonwealth_Marine_Regions/MapServer/WMSServer",
"http://www.environment.gov.au/mapping/services/ogc_services/Commonwealth_Marine_Reserves/MapServer/WMSServer",
"http://www.environment.gov.au/mapping/services/ogc_services/Conservation_Management_Zones/MapServer/WMSServer",
"http://www.environment.gov.au/mapping/services/ogc_services/Important_Wetlands/MapServer/WMSServer",
"http://www.environment.gov.au/mapping/services/ogc_services/EPBC_Referrals/MapServer/WMSServer",
"http://www.environment.gov.au/mapping/services/ogc_services/Key_Ecological_Features/MapServer/WMSServer",
"http://www.environment.gov.au/mapping/services/ogc_services/National_Heritage_List/MapServer/WMSServer",
"http://www.environment.gov.au/mapping/services/ogc_services/Ramsar_Upstream_Catchments/MapServer/WMSServer",
"http://www.environment.gov.au/mapping/services/ogc_services/Ramsar_Wetlands/MapServer/WMSServer",
```

**Comment by ljowen** [comment]
Updated above and email sent back to Jasmine.
https://github.com/TerriaJS/saas-catalogs-public/pull/433
