### ISSUE TITLE
NationalMap - Check and update Environment data services

### ISSUE THREAD

**Issue by AnaBelgun** [NICTA/nationalmap#1267]
Environment services list available here: https://gis.environment.gov.au/gispubmap/rest/services/ogc_services

Observations: 
- when adding the URL (above) it throws an error
- when adding layer groups (e.g. https://gis.environment.gov.au/gispubmap/rest/services/ogc_services/Australian_Marine_Parks/MapServer) it works

TODO:
- investigate and replace broken services on NatMap

**Comment by ljowen** [comment]
Updated Environment group with new working urls and removed wetlands of importance (DIWA dataset)

https://github.com/TerriaJS/saas-catalogs-public/pull/433
https://github.com/TerriaJS/saas-catalogs-public/pull/434
