### ISSUE TITLE
South Australian State data error

### ISSUE THREAD

**Issue by AnaBelgun** [NICTA/nationalmap#1271]
Investigate and fix the Groundwater Prohibition Area layer (from SA EPA) 

Here is the original data on data.sa.gov
https://data.sa.gov.au/data/dataset/groundwater-prohibition-area
- when adding GeoJSON URL on NatMap - error
- When adding the KMZ it works

**Comment by ljowen** [comment]
CRS on the geojson is EPSG:8059, which we don't support natively

**Comment by AnaBelgun** [comment]
Thanks @ljowen is it possible to harvest the KMZ?

**Comment by ljowen** [comment]
I've merged a PR which adds support for 8059, this dataset will be working next saas release

**Comment by ljowen** [comment]
Fixed: https://www.nationalmap.gov.au/#share=s-lS9RF1l7Pm8qylwaHWqGKlZ8pKs
