### ISSUE TITLE
Add IMOS and AODN geoservers to allowed hosts

### ISSUE THREAD

**Issue by florianm** [NICTA/nationalmap#129]
Could the Geoservers of IMOS and AODN be added to allowed hosts?

geoserver-123.aodn.org.au

geoserver.imos.org.au

If things go to plan, this would make the data shown on http://wa.aodn.org.au/waodn/ available to NationalMap.
Thanks!

**Comment by kring** [comment]
We can do that.  If you have any connection to the folks who run those servers, though, an even better solution is to push them to enable CORS.  CORS makes open data work, the proxy is just an ugly workaround. :)

**Comment by florianm** [comment]
Thanks @kring! I'll ask them to enable CORS.

I'm experimenting with a local NationalMap clone inside our corporate firewall to preview our internal CKAN and Geoservers (works great) - is the server-side proxy workaround to add the domains to the [corsdomains](https://github.com/NICTA/nationalmap/blob/master/datasources/000_settings.json#L9)? (Adding the IMOS and AODN geoserver domains to that setting didn't solve the CORS problem with my internal nationalmap.)

**Comment by kring** [comment]
You need to add them to `proxyDomains` in `wwwroot/config.json`.  You also need to make sure they're _not_ in `corsDomains`, because those are the domains that are assumed to support CORS and therefore bypass the proxy.

**Comment by florianm** [comment]
Ah, silly me. That makes heaps more sense, thanks! In that case, could you still add them for now until they've enabled CORS? I'll experiment with `proxyDomains` and could submit a PR for the 11_WA data source if I get them to work.

**Comment by kring** [comment]
Changes to NM need to be approved by PM&C, but I'll propose adding these servers to the proxy whitelist for the 15 November release, and it will most likely be ok with them.

**Comment by florianm** [comment]
Great, thanks! I'll experiment on my WA NationalMap [clone](http://map.beta.data.wa.gov.au/) (currently data.gov.au and vic gov't fail on CORS there) if that's ok.

**Comment by kring** [comment]
Oh yeah, you're welcome to do whatever you like with your own instance!

By the way, did you know NM provides URLs like this for all the states and territories:
http://map.beta.data.wa.gov.au/#wa

**Comment by florianm** [comment]
No I didn't know that... that's a very nice feature, thanks!

**Comment by florianm** [comment]
Hoots, IMOS and AODN both work with the magic proxyDomains setting at http://map.beta.data.wa.gov.au/#wa

Config at https://github.com/datawagovau/nationalmap/tree/datawagovau

I'll ask the IMOSes on which organisational level they'd like to sit. Mind that there's some recursion, as they also map Landgate's SLIP service, which publishes data from multiple agencies, and is also harvested into data.wa.gov.au. I feel some blacklisting would be appropriate in my NM config.
