### ISSUE TITLE
Backport GlobalDisclaimer from AREMI

### ISSUE THREAD

**Issue by stevage** [NICTA/nationalmap#131]
There seems to be repeated demand for this in new projects, so we should backport it: https://github.com/NICTA/aremi-natmap/commit/13015f63582da1dd7b9d93b624c60dc500d09289

**Comment by kring** [comment]
@stevage this should be a TerriaJS issue right?

**Comment by stevage** [comment]
Oh. I didn't intend it that way. Most map projects start by cloning NM, so I thought it should go in NM at least. But implementing it as a Terria feature would probably be even better.
