### ISSUE TITLE
Add a layer for Australian Geographical Indication (AGI) areas

### ISSUE THREAD

**Issue by dcrossleyau** [NICTA/nationalmap#141]
I am not sure if such a layer is available. Here is some net research:

http://onlinelibrary.wiley.com/doi/10.1111/ajgw.12145/abstract
Verdonk, N.R., Wilkinson, K.L. and Bruwer, J. (2015), Importance, use and awareness of South Australian geographical indications. Australian Journal of Grape and Wine Research. doi: 10.1111/ajgw.12145

https://www.wineaustralia.com/en/Production%20and%20Exporting/Register%20of%20Protected%20GIs%20and%20Other%20Terms/Geographical%20Indications.aspx

**Comment by stevage** [comment]
Probably better to request a dataset here: https://datagovau.ideascale.com/
