### ISSUE TITLE
problems when using https://www.nationalmap.gov.au

### ISSUE THREAD

**Issue by tobybellwood** [NICTA/nationalmap#150]
when navigating to the https instance of www.nationalmap.gov.au (accidentally), any catalogue item using wfs is blocked (in Chrome), and CORS warns in IE11.  ABS.Stat ITT lookup doesn't work in IE11.

Worth noting that a google search for "NationalMap" directs users to the https site.

**Comment by kring** [comment]
Should _should_ be fixed by TerriaJS/terriajs#1163.  We'll have a test server with https up tomorrow to try it out.

**Comment by kring** [comment]
@tobybellwood can you confirm that the problem you originally saw is gone?  It seems ok in my testing, after some recent changes.  You can test with:
https://staging.nationalmap.nicta.com.au/

**Comment by tobybellwood** [comment]
agreed - looks like it works in staging.

**Comment by kring** [comment]
Great, thanks!
