### ISSUE TITLE
reference to non-existent Data Catalogue tab

### ISSUE THREAD

**Issue by DanielBaird** [NICTA/nationalmap#151]
Text in the "Now Viewing" section, when there are no datasets selected for display, reads "Add data using the Data Catalogue tab".  There is no Data Catalogue tab... I think that text should refer to the Data Services tab?

![screen shot 2015-11-30 at 11 07 39 am](https://cloud.githubusercontent.com/assets/25352/11461625/9e55ce44-9752-11e5-896f-041da555218b.png)

**Comment by stevage** [comment]
Ah, thanks. On NEII Viewer the tab has been renamed, but obviously not that message.
