### ISSUE TITLE
Add Australian Communications and Media Authority (ACMA) datasets

### ISSUE THREAD

**Issue by kring** [NICTA/nationalmap#154]
From a user within the NSW government:

> Many thanks for the impressive demos last week and your hospitality at NICTA. As discussed at the demo, the Australian Communications and Media Authority (ACMA) have an online database of all licensed radiocommunications transmitters around Australia. This data is freely available online and is used on a daily basis by regulatory authorities, spectrum planners and users.
> 
> 
> The online search database is here:
> http://web.acma.gov.au/pls/radcom/register_search.main_page
> 
> 
> 
> The downloadable copy is here:
> http://www.acma.gov.au/Industry/Spectrum/Radiocomms-licensing/Register-of-radiocommunications-licences/radiocomms-licence-data
> 
> 
> 
> Hopefully the ACMA data can be added to National Map as this would be very useful for those involved with radio communications community (such as myself). Let me know if you need any more information.

**Comment by axman6** [comment]
I built a service to put this on AREMI which is now live (Infrastructure -> Communications -> Radio licences - ACMA). I spoke to some ACMA people at the NM forum the other day and they said they have a new API which should be public soon. I think it'd be fine to use my service, but it is missing some data compared to the ACMA website.

**Comment by meh9** [comment]
So, AREMI just added the ACMA Radio License database:

http://nationalmap.gov.au/renewables/#share=k3NPPc

We are still working on this service, so expect things to change a little over the next couple of months.

Init is here:

https://github.com/NICTA/aremi-natmap/blob/master/datasources/aremi/custodian/Australian_Communications_and_Media_Authority/Radio_Licenses.ejs

**Comment by kring** [comment]
Awesome, thanks guys!
