### ISSUE TITLE
Consider adding the new Geoscience Australia LiDAR derived 25m DEM

### ISSUE THREAD

**Issue by meh9** [NICTA/nationalmap#169]
GA recently released a new 25m DEM image derived from LiDAR data, you might want to consider adding it:

https://github.com/NICTA/aremi-natmap/pull/25/files

**Comment by stevage** [comment]
Thanks Mats. Just in case anyone was tempted to simply merge this, pointing out that it contains EJS tags not supported by NM :)

**Comment by meh9** [comment]
5m resolution DEM is now available: http://services.ga.gov.au/gis/rest/services/DEM_LiDAR_5m/MapServer

**Comment by stevage** [comment]
Closed by https://github.com/TerriaJS/NationalMap-Catalog/pull/17
