### ISSUE TITLE
Provide direct downloads for Statistical Boundaries

### ISSUE THREAD

**Issue by stevage** [NICTA/nationalmap#174]
People always want the SA2 etc boundaries - we should include links to download them.

**Comment by kring** [comment]
Download links can be found near the bottom of this page on the ABS web site:
http://www.abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/1270.0.55.001July%202011?OpenDocument

**Comment by stevage** [comment]
Well, I was actually just thinking of downloads from our GeoServer, eg [SA2](http://geoserver.nationalmap.nicta.com.au/admin_bnds_abs/admin_bnds/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=admin_bnds:SA2_2011_AUST&maxFeatures=50&outputFormat=SHAPE-ZIP).

Although it's true that ABS web locations are probably extremely stable.

**Comment by kring** [comment]
It's always best to refer users to the original source of the data when possible, right?

**Comment by stevage** [comment]
Interesting question. There are arguments both ways, but I think you're probably right for this one.
