### ISSUE TITLE
Update logos and company names

### ISSUE THREAD

**Issue by kring** [NICTA/nationalmap#177]
On the About page:
* The Department of Communications log should be changed to a Prime Minister and Cabinet logo.
* The NICTA logo should be changed to a Data61 logo.

On the map:
* The NICTA credit should be changed to a Data61 credit.

**Comment by hilarycinis** [comment]
@philipgrimmett there are some assets for this in the trello board in "to do" now. It's not the full suite but could be applicable.

**Comment by kring** [comment]
This was fixed in the 15 Feb release.
