### ISSUE TITLE
Add innovation-by-region dataset

### ISSUE THREAD

**Issue by bsimyo** [NICTA/nationalmap#190]
This dataset has innovation metrics by SA3 and is in data.gov.au at http://data.gov.au/dataset/sa3-region-innovation-data-2009-14
It's also used by and downloadable at
http://www.industry.gov.au/Office-of-the-Chief-Economist/Pages/National-Innovation-Map.html

**Comment by stevage** [comment]
Obviously the best thing here would be for the data custodian to republish this as a csv-geo-au. It's very close. They just need to:

1. Choose only the "data" tab.
2. Rename "SA3 Code" to "SA3_code"
3. Remove the "Latitude" and "Longitude" columns.
4. Replace "Year" with "Date" and use yyyy-mm-dd format.

I don't think there's much we can do with their existing .xslx, short of transforming it ourselves and and storing a copy in the NM codebase, which doesn't seem like a great thing from either a data policy or software maintenance perspective.

**Comment by bsimyo** [comment]
Yes, fully agree.

**Comment by bsimyo** [comment]
Actually the csv-geo-au format doesn't specify how dates should be specified.  I'll put in an issue for that.

**Comment by bsimyo** [comment]
And I'll leave this issue open as I think that once this data set in on data.gov.au, that we should have links to it on the main menu (subject to approval from pmc)

**Comment by ajbar7** [comment]
So I thought I'd give this a test before I gave it to Industry to play with and I've hit a bit of an issue. It seems to only be pulling the data from 2009 and giving an error about the duplicate SA3s.

![innovation-sa3](https://cloud.githubusercontent.com/assets/7380633/12541012/d15f29c8-c364-11e5-9817-b735f801c411.png)

I could've possible put the file together wrong. 
 
[SA3-Region-Innovation-Data-2009-14.txt](https://github.com/NICTA/nationalmap/files/102670/SA3-Region-Innovation-Data-2009-14.txt) - Convert back to CSV

**Comment by stevage** [comment]
The good news: that file works great with the latest version of NM, about to be deployed.

We should [be a bit smarter about which column we use as the data variable though](https://github.com/TerriaJS/terriajs/issues/1322).
