### ISSUE TITLE
csv-geo-au should specify date format

### ISSUE THREAD

**Issue by bsimyo** [NICTA/nationalmap#192]
I think we should support a range of different date formats of different resolutions eg yyyy, yyyy-mm, yyyy-mm-dd @stevage @RacingTadpole - what do you think makes sense?
Sample data set with year (not yet csv-geo-au but can easily be made so at http://data.gov.au/dataset/sa3-region-innovation-data-2009-14 )

**Comment by stevage** [comment]
Yes, those three make sense to me, plus the two versions of yyyy-mm-dd with time (with and without timezone).

I thought we had previously implemented a way to have start and end dates as well (so that a row represents a clearly defined span of time) but don't see it now.

**Comment by RacingTadpole** [comment]
Sounds sensible. In fact YYYY and YYYY-MM are both recognised by Terria now, as a result of https://github.com/TerriaJS/terriajs/pull/1224.

Terria also understands datetimes that use the ISO8601 format, eg. "2016-01-03T12:15:59.1234Z". I have just submitted a pull request https://github.com/TerriaJS/terriajs/pull/1251 which also adds "2016-01-03 12:15:59" (ie. without the "T") and "2016/01/03 12:15:59" (ie. with slashes, no "T").

Being able to set an explicit span of time would make sense too; ISO8601 specifies a format for that, which could make sense. Currently terria doesn't recognise that.

@stevage, do you want to update the csv-geo-au specs?

**Comment by stevage** [comment]
ISO8601 has some pretty kooky formats for things like intervals and recurring dates, many of which have never been widely adopted.  I'd suggest a more straightforward `date` and `date_end` combination instead.

I've updated csv-geo-au to 1.3 now.
