### ISSUE TITLE
Update Population Density service endpoint (decommissioned 05/02/2016)

### ISSUE THREAD

**Issue by philipgrimmett** [NICTA/nationalmap#197]
The same dataset is being migrated to a new ArcGIS 10.2 server.

New endpoint: http://services.ga.gov.au/gis/rest/services/NEXIS_Residential_Population_Density/MapServer

**Comment by axman6** [comment]
I think this might also be relevant to NICTA/aremipnatmap - @meh9?

**Comment by meh9** [comment]
@axman6, AREMI was updated to use the new service in November.

**Comment by stevage** [comment]
See https://github.com/NICTA/nationalmap/pull/214

**Comment by stevage** [comment]
Did this in March.
