### ISSUE TITLE
It's easy for people to inadvertently create sites that look like they are the official NationalMap

### ISSUE THREAD

**Issue by bsimyo** [NICTA/nationalmap#200]
People creating their own maps are likely to fork NM (rather than coding from scratch using TerriaJS) and people will tend to keep in the NM logo and the "Australian Government" logo.  Organisations building maps are likely to change this but I can imagine some people setting ones up for testing and not getting round to changing these.  This would cause confusion with the actual NationalMap and look like are Australian Government sites when they aren't. (I have just seen one beta site doing this which will no doubt be changed before production but it's what made me realise that we should really address this). 

Ideally, it would be good if the NM codebase had some other default logos (eg the NM one replaced with one saying eg "a Terria Map" and the "Australian Government" one saying eg "built on Data61 technology") so anyone creating a fork of NM isn't accidentally passing their site off as the Australian Government's NationalMap.  Then the NM and Aust Govt logos could be added in deployment scripts.  Doable?

**Comment by stevage** [comment]
Agreed. I did some work towards this. Will keep on it.

(I also think it would be better if our local copies were more obviously distinguished from the production deployed system.)

**Comment by meh9** [comment]
Maybe we should make branding be set from the config?

**Comment by axman6** [comment]
I'd love to be able to use a template, or even just an HTML snippet which gets injected.

**Comment by stevage** [comment]
I put the HTML snippets in the config. @meh9 you might want to double check the implications for AREMI
