### ISSUE TITLE
Add ABC photo stories to the catalog

### ISSUE THREAD

**Issue by RacingTadpole** [NICTA/nationalmap#230]
The [ABC photo stories](http://data.gov.au/dataset/abc-local-online-photo-stories-2009-2014) (listed on data.gov.au) would look great on the map.

To do this well, would require https://github.com/TerriaJS/terriajs/issues/1407 and https://github.com/TerriaJS/terriajs/issues/1408.

**Comment by RacingTadpole** [comment]
Actually I'm not clear on why this doesn't appear in the catalog at the moment?

**Comment by AlexGilleran** [comment]
I think it falls foul of the filterQuery: `fq=+(res_format%3awms%20OR%20res_format%3aWMS%20OR%20res_format%3acsv-geo-au%20OR%20res_format%3aaus-geo-csv)` ? Probably not setup as csv-geo-au even though it kind of works.

**Comment by RacingTadpole** [comment]
That sounds right - but then I'm not sure why eg. [Cardinia shire's e-waste data](http://data.gov.au/dataset/cardinia-shire-e-waste-collection-points/resource/321c2cb1-6c34-4746-874b-2422da0339db) does appear ... its `format` is `csv`, the same as the [ABC one](http://data.gov.au/dataset/abc-local-online-photo-stories-2009-2014/resource/d73f2a2a-c271-4edd-ac45-25fd7ad2241f). Maybe the `res_format` isn't shown on those pages.

**Comment by stevage** [comment]
The Cardinia e-waste data layer that appears is WMS though, caused by the include GeoJSON file - am I missing something?

Why not just directly include a link to this dataset in National Data Sets? (with @tobybellwood's approval...)

**Comment by RacingTadpole** [comment]
Ah right, thanks Steve. Yes, including it directly would be simpler.
