### ISSUE TITLE
Hide ABS ITT dataUrl

### ISSUE THREAD

**Issue by stevage** [NICTA/nationalmap#233]
We shouldn't show a "download" URL for the ABS ITT service, because we only have the .jsp endpoint, which is not useful.

**Comment by RacingTadpole** [comment]
Good plan. Note the ABS data is usually combined from several URLs (eg. the Age 0-4 is one download, Age 5-9 is another).

This PR changes it to show only one of these download URLs, which may be misleading, especially as the downloaded values are in a column labelled simply "value". The user may think this has the values they selected, but in fact it might only have values for Age 0-4.

I suggest we either show no URL, show all the URLs, or show only one but include a warning that this is not the complete data.

**Comment by stevage** [comment]
Just realised that [that PR](https://github.com/TerriaJS/terriajs/pull/1413) hasn't been merged yet.

**Comment by RacingTadpole** [comment]
That PR will be out-of-date soon, when ABS moves to the SDMX-JSON API, so I've closed it now without merging. 

Let's keep this issue open to remind us to make sure the URLs make sense with the new API.
