### ISSUE TITLE
Group all local government data

### ISSUE THREAD

**Issue by stevage** [NICTA/nationalmap#234]
Currently some councils are under data.gov.au and others are under Data Providers, and probably some are under South Australian Government. This makes sense to us because that's where the data is housed, but it doesn't really make any sense to end users.

Assuming we can make this work, wouldn't it be better to have a "Local Government" group, with them all there (and hopefully not present under the other groups)?

I think this would require:

- some kind of filter on data.gov.au to identify the right organisations ("city of ...", "...shire council", and maybe a few specifics), then implement a negative filter to remove those results from there.
- similarly for data.sa.gov.au
- move City of Melbourne and City of Brisbane

Could be controversial. @tobybellwood ?

**Comment by tobybellwood** [comment]
Agree broadly - would need some work to implement nicely (most likely some sort of LGA master list lookup/X-Ref) - But would make it easier to sort and organise.  WA are looking to add more LGAs to their portal too

**Comment by stevage** [comment]
Linked to #25
