### ISSUE TITLE
Use ArcGIS Online MapServers for ACT Government

### ISSUE THREAD

**Issue by kring** [NICTA/nationalmap#240]
http://data.actmapi.act.gov.au/arcgis/rest/services/actmapi

**Comment by kring** [comment]
Extents on this server are specified in a particular zone of GDA94.  We'll need support for this in TerriaJS.

**Comment by stevage** [comment]
Specifically http://spatialreference.org/ref/epsg/gda94-mga-zone-55/

The short term hack would be to just override all extents to be the boundaries of the ACT

**Comment by stevage** [comment]
Wait, we haven't actually added the mapservers to the catalog :)

**Comment by kring** [comment]
GitHub helpfully closed this again, but it shouldn't have, right?

**Comment by stevage** [comment]
Well, that shouldn't have. But [this](https://github.com/TerriaJS/NationalMap-Catalog/commit/7083890719f8ac39f860b2970d975dd8e2064ca4) should have.

**Comment by AnaBelgun** [comment]
Custodian (info page): To add Office of the Surveyor-General spatialdata@act.gov.au as contact details and something relating to licencing: Creative Commons Attribution 4.0 Australian Capital Territory (To be confirmed until 1 July 2016).

**Comment by AnaBelgun** [comment]
Will ask ACT Gov team to add that information under 'copyright' on http://data.actmapi.act.gov.au/arcgis/rest/services/actmapi/actmapi_overview/MapServer

**Comment by meh9** [comment]
@AnaBelgun if they follow how GA does it and add the copyright notice using the element `copyrightText` then it will show up with no further action from us as we now look for that in the service metadata: https://github.com/TerriaJS/terriajs/issues/1188

**Comment by vanpuk** [comment]
Hi All,
Thanks for meeting with Anthony last week. At this point all our spatial services set up through http://data.actmapi.act.gov.au/arcgis/rest/services/actmapi/actmapi_overview/MapServer should be set with the appropriate license.  The Terms of use will accompany all CCBY datasets post 1st July.  The Web services should be tagged with an appropriate category, as shown in the quick search categories (http://actmapi.actgov.opendata.arcgis.com/).
It would be great to get some assistance and guidance on our current services specifically how metadata and license should be imbedded within the services.
Cheers Kristy

**Comment by stevage** [comment]
Hi Kristy,
By "should be set with", do you mean "I think they are already set with" (which [doesn't seem to be the case](http://data.actmapi.act.gov.au/arcgis/rest/services/actmapi/actmapi_overview/MapServer/7) - no "copyright text" there) or "I would like you to set them with"? We can do the latter as a temporary measure, but it's really better for the licensing metadata to be stored in the same place as the data - in your ArcGis system.

If you'd like us to do that, could you provide the exact text to apply to every item?

> The Web services should be tagged with an appropriate category, as shown in the quick search categories 

Similarly, I'm not quite sure what you mean by "should be tagged with an appropriate category". You mean that you think there is already a category present?

You can see how this is looking so far:

http://nationalmap.gov.au/#https://rawgit.com/TerriaJS/NationalMap-Catalog/dev/build/nm.json&act

**Comment by vanpuk** [comment]
Hi @stevage,
When I said "should" I was hoping! Is it possible to arrange a technical meeting with my staff to figure out how we can transport the metadata and license information with the WMS?

**Comment by stevage** [comment]
Looks like @meh9 may be able to help.

**Comment by AnaBelgun** [comment]
When clicking on ACT Government catalogue item, to alert users "datasets to be available by 1 July 2016" instead of "not available since January 2016".

**Comment by stevage** [comment]
Here's the list as they'd like it:

https://docs.google.com/spreadsheets/d/1WzGy5wO5UPwsuWgQBWZ895BrvvptfCKs1X413ocXVhk/edit#gid=833819545
