### ISSUE TITLE
Some datasets are failing

### ISSUE THREAD

**Issue by RacingTadpole** [NICTA/nationalmap#244]
These data sets are giving error messages "Unusable ArcGIS Mapserver layers metadata":
- National Data Sets -> Land -> Gravity Anomaly
- National Data Sets -> Land -> Magnetic Intensity

And data.gov.au's IP Australia dataset crashes my Chrome - even just accessing its info.

**Comment by meh9** [comment]
Those two services have gone away, you will want to switch to specific layers from this service:

http://services.ga.gov.au/gis/rest/services/Geophysical_Grids/MapServer

In AREMI we just grab all of them:

https://github.com/NICTA/aremi-natmap/blob/2016-03-22/datasources/aremi/custodian/Geoscience_Australia/Geothermal_layers.ejs#L38
