### ISSUE TITLE
Broken items in catalogue 15-04-16 release

### ISSUE THREAD

**Issue by tobybellwood** [NICTA/nationalmap#246]
Please can the following catalogue items be fixed in the next remote catalogue update?

Framework
> Defence Practice Areas -http://services.ga.gov.au/gis/rest/services/Defence_Restricted_Areas/MapServer/0
> Defence Prohibited Areas - http://services.ga.gov.au/gis/rest/services/Defence_Restricted_Areas/MapServer/2
> Defence Training Areas - http://services.ga.gov.au/gis/rest/services/Defence_Restricted_Areas/MapServer/1
> Electricity Transmission Lines - http://services.ga.gov.au/gis/rest/services/Electricity_Infrastructure/MapServer/2
> Electricity Transmission Substations - http://services.ga.gov.au/gis/rest/services/Electricity_Infrastructure/MapServer/1
> Onshore Gas Pipelines - http://services.ga.gov.au/gis/rest/services/Oil_Gas_Infrastructure/MapServer/1
> Onshore Oil Pipelines - http://services.ga.gov.au/gis/rest/services/Oil_Gas_Infrastructure/MapServer/0

Ta!

**Comment by kring** [comment]
Fixed by TerriaJS/NationalMap-Catalog#3.
