### ISSUE TITLE
Add permalink to latest built catalogue in README.md

### ISSUE THREAD

**Issue by tobybellwood** [NICTA/nationalmap#249]
in the https://github.com/TerriaJS/NationalMap-Catalog repo eg. http://nationalmap.gov.au/#clean&https://rawgit.com/TerriaJS/NationalMap-Catalog/master/build/nm.json

**Comment by stevage** [comment]
Ok, but why? :)

**Comment by stevage** [comment]
Oh, I get it - it's a preview of the latest catalog file (as opposed to the one in production). Done.

**Comment by tobybellwood** [comment]
yup - thanks!! (can't imagine many people other than us using it, but hey!)
