### ISSUE TITLE
Add feedback mechanism for new UI rollout

### ISSUE THREAD

**Issue by kring** [NICTA/nationalmap#252]
We're planning to have a version of NationalMap with the new UI hosted on Data61 infrastructure by 15 May.  We should make it really easy for people to send us feedback about it.  At a minimum, there should be a prominent "email feedback" link, but better would be something more automatic and integrated.

**Comment by tobybellwood** [comment]
good thinking - are we able to get the feedback too?

**Comment by kring** [comment]
@tobybellwood yes we'll make sure of it!

**Comment by kring** [comment]
This is done in the newui branch.
