### ISSUE TITLE
Licensing for Tasmanian Datasets

### ISSUE THREAD

**Issue by tobybellwood** [NICTA/nationalmap#254]
The licenses stipulated in the Catalogue entries for the Tasmanian datasets do not match the licenses provided by the  ArcGIS server (http://services.thelist.tas.gov.au/arcgis/rest/services) 

Example: http://services.thelist.tas.gov.au/arcgis/rest/services/Basemaps/Orthophoto/MapServer is CC-BY-NC-ND and we've linked to http://creativecommons.org/licenses/by/2.5/au/

**Comment by meh9** [comment]
If these were all changed to using the MapServers and the licensing details removed then the correct licensing details will be included automatically since we now grab the `copyrightText`.

**Comment by stevage** [comment]
Huh. So ArcGIS Server's WMS endpoint doesn't include the licence metadata. [Anywhere](http://localhost:3001/proxy/http://services.thelist.tas.gov.au/arcgis/services/Basemaps/Orthophoto/ImageServer/WMSServer?service=WMS&version=1.3.0&request=GetCapabilities).

**Comment by stevage** [comment]
Unfortunately some of the layers don't have a MapServer end point, and we don't terriajs/terriajs#1458.

**Comment by kring** [comment]
It should be super easy to add ImageServer support.  I can do it if you don't want to get involved.

**Comment by stevage** [comment]
Yeah, good idea. Although I have done this the braindead way for now.

**Comment by kring** [comment]
Great, that way we don't necessarily have to rush to add ImageServer in the release next week.  Thanks!
