### ISSUE TITLE
add NRMR, ADD & TR to csv-geo-au

### ISSUE THREAD

**Issue by tobybellwood** [NICTA/nationalmap#255]
I note from the wiki that these areas are currently unsupported - is there a reason for not including them, or can it be done?

**Comment by steve9164** [comment]
Tourism regions are currently supported on nationalmap (see the [regionMapping.json](https://github.com/NICTA/nationalmap/blob/master/wwwroot/data/regionMapping.json#L504-L528) region map definitions). TR 2015 can be used with a column name: `tr`, `tr_code` or `tr_code_2015`. TR 2013 can be used with the column name: `tr_2013` or `tr_code_2013`.

I'll add the others and then update the documentation.

**Comment by kring** [comment]
Fixed by #258.
