### ISSUE TITLE
Rename and add Commonwealth Electoral Divisions

### ISSUE THREAD

**Issue by tobybellwood** [NICTA/nationalmap#256]
Please can we add the AEC 2016 Commonwealth Electoral Boundaries to NationalMap.

Please ensure that these are labelled clearly as "Commonwealth Electoral Divisions (2016)"

Pleas rename the current layer (admin_bnds:COM20111216_ELB_region)  "Commonwealth Electoral Divisions (2011)"

Can the 2016 boundaries also be added to csv-geo-au - we'll need to migrate the synonyms from 2011 to 2016.  Happy to discuss.

Name or code	Field with year	Field without year	Synonym
ced_code_2016 - ced_code - ced
ced_name_2016 - ced_name

**Comment by steve9164** [comment]
We're working on adding 2016 Commonwealth Electoral Boundaries to nationalmap and currently have a development branch that supports these (from data we created by merging the old national boundaries with new boundaries for NSW, ACT & WA) with column name `ced_aec_2016` (we can easily change this though). The data files we used (from the AEC) don't have any attribute that can be used as a code. The currently supported CED regions that have a code come from ABS not AEC, however I couldn't find any 2016 updated CED data on their site.

**Comment by tobybellwood** [comment]
@steve9164 - I don't know about numbering for the new divs, but the AEC should be used for these boundaries (as distinct from the ABS ones) - as per

http://results.aec.gov.au/17496/Website/Downloads/GeneralEnrolmentByDivisionDownload-17496.csv

I'll see what I can find out.

**Comment by tobybellwood** [comment]
Updated id mappings now at http://www.aec.gov.au/About_AEC/cea-notices/files/2016/prdelms.gaz.statics.160509.14.47.56.csv

**Comment by kring** [comment]
Fixed by #257
