### ISSUE TITLE
newui - icons not working in IE11.0.31

### ISSUE THREAD

**Issue by tobybellwood** [NICTA/nationalmap#260]
None of the icons are loading in IE11 on our network - is this an issue with ::before?

![image](https://cloud.githubusercontent.com/assets/4373945/15307099/563dcb34-1c13-11e6-9e15-b7e5fb47600e.png)

**Comment by kring** [comment]
That same version of IE11 is showing icons from the Data61 network, so presumably it's network related rather than a problem with the browser itself.  Is it broken in Chrome, too, on your network?

**Comment by kring** [comment]
Eagle-eye @chloeleichen noticed that all the custom fonts are wrong in your screenshot.  Do you know if IE is configured to block custom fonts on your network?  That would explain the missing icons, too, because they're implemented as a custom font.  Can you check the browser console and see if there are any interesting messages?

**Comment by kring** [comment]
Can you check the "Font Download" setting:

![image](https://cloud.githubusercontent.com/assets/924374/15307940/70bed8b0-1c1b-11e6-91f2-cd0434bf27ae.png)

The dialog on the right is accessed by clicking the Custom Level button on the left.

I get the same behavior you're seeing if I set it to Disabled.

**Comment by tobybellwood** [comment]
Looks like the ability to edit the security levels is locked for us - most likely it's a GP thing...

![image](https://cloud.githubusercontent.com/assets/4373945/15308857/d7b46f54-1c24-11e6-9d4e-3e3b1a9ddf96.png)

**Comment by tobybellwood** [comment]
I'll continue this offline...  If there is a broader issue, we can reactivate?

**Comment by kring** [comment]
Fixed by TerriaJS/terriajs#1710.
