### ISSUE TITLE
newui - unable to send feedback from PM&C

### ISSUE THREAD

**Issue by tobybellwood** [NICTA/nationalmap#261]
possibly a network issue from our side?

![image](https://cloud.githubusercontent.com/assets/4373945/15307155/d1c86372-1c13-11e6-8f85-22fede602b92.png)

**Comment by kring** [comment]
That's weird!  Can you screenshot the details of the request in Chrome's network tab?  It should be a POST to `/feedback`.

**Comment by kring** [comment]
Nevermind, it's an IE11 problem, not a network problem.  I'll fix it up.

**Comment by kring** [comment]
Fixed by https://github.com/TerriaJS/terriajs/commit/9186203d66205c6eb5cc3bfb9f9bf1e8f2ffcf72
