### ISSUE TITLE
Inconsistent feature info box download in COM ELB 2016 / Incorrect legend

### ISSUE THREAD

**Issue by tobybellwood** [NICTA/nationalmap#262]
Some of the ELBs in the 2016 layer only allow download of the feature info box as a CSV, some as a JSON (seems to be the new boundaries - WA, ACT, NSW)

![image](https://cloud.githubusercontent.com/assets/4373945/15663936/f98021b8-2742-11e6-9665-8b1d3de2a40a.png)

Also the legend has an odd default title of "blue line" - it's actually purple, but the legend could be more helpful?

**Comment by kring** [comment]
@tobybellwood we should be able to fix the legends with a catalog update.  I suspect the inconsistent feature info boxes are a result of our merging boundaries from multiple sources, and will go away once we're using the official 2016 boundaries from AEC.  Does that sound right to you?

**Comment by tobybellwood** [comment]
Looks like @stevage has it covered in https://github.com/TerriaJS/terriajs/issues/1581
