### ISSUE TITLE
Geelong data not displaying correctly

### ISSUE THREAD

**Issue by CraigDPalmer** [NICTA/nationalmap#3]
Hi,
1. The "Central Geelong 3D Massing Model" (from Data.gov.au) layer is not displaying. When I click on it it takes me out to the Atlantic Ocean and does not display any models
2. The Geelong Roofprints layer generates an error message "error accessing catalogue item". But it does display if you zoom in closer and tilt into a oblique view. It seems to have a problem with the full extent and ortho view.
Regards
Craig

**Comment by kring** [comment]
> The "Central Geelong 3D Massing Model" (from Data.gov.au) layer is not displaying. When I click on it it takes me out to the Atlantic Ocean and does not display any models

National Map is accessing the WMS version of this dataset.  I'm not sure if Geelong folks created the WMS resource explicitly, or if it was automatically created by data.gov.au from the KML or GeoJSON.  In any case, the extent in the metadata is `west: 0deg, south: 0deg, east: -1.0deg, north: -1.0deg` which is not a valid extent.  Probably need to report this to Geelong.

> The Geelong Roofprints layer generates an error message "error accessing catalogue item". But it does display if you zoom in closer and tilt into a oblique view. It seems to have a problem with the full extent and ortho view.

The WMS server is reporting errors for seemingly-valid requests like this:
http://data.gov.au/geoserver/geelong-roofprints-kml/wms?transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&service=WMS&version=1.1.1&request=GetMap&layers=41527e85_0907_4faf_b5f4_e9655b23d128&srs=EPSG%3A3857&bbox=16084796.736106213%2C-4637587.380118214%2C16104364.615347218%2C-4618019.500877209&width=256&height=256

The error is:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE ServiceExceptionReport SYSTEM "http://data.gov.au:80/geoserver/schemas/wms/1.1.1/WMS_exception_1_1_1.dtd"> <ServiceExceptionReport version="1.1.1" >   <ServiceException code="internalError">
      More than 1000 rendering errors occurred, bailing out.
Latitude 90°00.0&apos;S is too close to a pole.
</ServiceException></ServiceExceptionReport>
```

The requested extent is not especially near the south pole, so it's not clear to me what's going on here.  @maxious can you provide any insight here?

**Comment by maxious** [comment]
See https://github.com/TerriaJS/terriajs/issues/673

It gets automatically ingested as if it were a 2D KML but the pipeline for 3D building streaming isn't known yet.
