### ISSUE TITLE
GA WMS layers not centring correctly

### ISSUE THREAD

**Issue by stevage** [NICTA/nationalmap#41]
GA has just enabled their new services ([for example](http://www.ga.gov.au/gis/services/topography/Dynamic_National_Map_Hydrography_and_Marine/MapServer/WMSServer)). They display in NM, but clicking on a layer name (for example, Elevation > Reefs and Shoals) zooms to 0,0.

The [`getCapabilities` response](http://www.ga.gov.au/gis/services/topography/Dynamic_National_Map_Elevation_Relief_and_Physiography/MapServer/WMSServer?service=WMS&version=1.3.0&request=GetCapabilities) looks superficially correct:

```
<EX_GeographicBoundingBox>
<westBoundLongitude>112.92145</westBoundLongitude>
<eastBoundLongitude>153.46622</eastBoundLongitude>
<southBoundLatitude>-43.65649</southBoundLatitude>
<northBoundLatitude>-11.00691</northBoundLatitude>
</EX_GeographicBoundingBox>
<BoundingBox CRS="CRS:84" minx="112.92145" miny="-43.65649" maxx="153.46622" maxy="-11.00691"/>
<BoundingBox CRS="EPSG:4326" minx="-43.65649" miny="112.92145" maxx="-11.00691" maxy="153.46622"/>
<BoundingBox CRS="EPSG:4283" minx="-43.65649" miny="112.92145" maxx="-11.00691" maxy="153.46622"/>
```

You can see the new list [here](http://nationalmap.research.nicta.com/#clean&https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2F6ad807d7ab40c16ff61e%2Fraw%2F08e2a3473d6fd22327ae00266d27e88e3079cc74%2Fdatasource.json) temporarily.

**Comment by kring** [comment]
If you hit the Info button, you'll see:
`Layer information not found in GetCapabilities operation response.`

Apparently the `layers` parameter doesn't match a layer name in the GetCapabilities?

Because of this, NM doesn't know the bounding box, so it can't zoom to it.

I'd recommend accessing GA's ArcGIS Server via `ArcGisCatalogGroup` and `ArcGisMapServerCatalogItem` rather than WMS anyway, if possible.

**Comment by kring** [comment]
Ah, I see, `layers` is specifying multiple layers.  NM should get the metadata of all the layers in this case, and then union their bounding boxes.  But it's not that smart.  Specifying the `rectangle` explicitly in the init file would work, of course.

**Comment by stevage** [comment]
Hmm, even if it chose the bounding box of any of them randomly that would probably work in this case.

I can probably workaround it using `itemProperties`. Tempted to get creative and:

```
itemProperties: { 
  itemProperties: {
   Rectangle: ...
  }
}
```

:)

**Comment by kring** [comment]
It doesn't look like you're using automatic GetCapabilities querying, it's all hard-coded into the init file anyway.  So why do you need to do the `itemProperties` thing?

**Comment by stevage** [comment]
Looks easier to fix than to workaround, so I'm doing that.
