### ISSUE TITLE
National Map v2017-06-15 pre-release test - Zoom to extent feature unavailable

### ISSUE THREAD

**Issue by EhsanCanberra** [NICTA/nationalmap#523]
Layer: Local Government/Tasmania/Glenorchy/Glenorchy City Council Gas (KML)

- Loaded the dataset as expected on map zoomed to (default) continent Australia
- Tried to use 'Zoom to Extent' function to zoom into the dataset as it was not visible
- Zoom to extent inactive
- Not familiar with the city - had to manually zoom into Tasmania to visually find the dataset

![slide25](https://user-images.githubusercontent.com/22827786/27369217-52e00ac0-569a-11e7-8dad-8f84def56005.JPG)
![slide26](https://user-images.githubusercontent.com/22827786/27369218-52eae0a8-569a-11e7-8289-61751487def0.JPG)

**Comment by RacingTadpole** [comment]
Zoom-to-extent with KML is a noted issue in Terria - https://github.com/TerriaJS/terriajs/issues/2547 .
