### ISSUE TITLE
Remove GA topography service from data services

### ISSUE THREAD

**Issue by bsimyo** [NICTA/nationalmap#58]
GA have said that most or all data under the Topography data provider will be available through new data collection file with the new GA data services (and with better naming).  So we should remove the Topography line under "data providers"

**Comment by kgrochow** [comment]
All that does is point to our topo_250k server which will be retired when their services are ready, so not a problem.

**Comment by kring** [comment]
It's already gone in the `ga-new-datasources` branch.

**Comment by kgrochow** [comment]
fixed by #100
