### ISSUE TITLE
Change NM mailing list in index.js

### ISSUE THREAD

**Issue by bsimyo** [NICTA/nationalmap#66]
We are still getting the odd support request to nationalmap@lists.nicta.com.au
I assume it's because of this:
       supportEmail: 'nationalmap@lists.nicta.com.au',
in this:
     https://github.com/NICTA/nationalmap/blob/master/index.js 

This should be nationalmap@communications.gov.au

**Comment by bsimyo** [comment]
It would be worth checking if there is anything else in there that needs similar changes for the official government-hosted service

**Comment by kgrochow** [comment]
the comms address is only being presented in the help files and there are some remnant lists.nicta entries in terriajs.  Should be easy enough to clean up.

**Comment by kring** [comment]
Fixed by #67
