### ISSUE TITLE
Left column of help text doesn't scroll

### ISSUE THREAD

**Issue by bsimyo** [NICTA/nationalmap#77]
If the window size isn't big enough for display of the full left hand text (ie headings) vertically, it is off the bottom of the screen and can't be reached.  The right hand column has a scroll bar so is fine. Tried on Firefox and Chrome and is a problem on both.

**Comment by hilarycinis** [comment]
@philipgrimmett will find template to handle redesign of about and help pages

**Comment by kring** [comment]
Fixed by @philipgrimmett's new pages.
