### ISSUE TITLE
Add support for AEC electoral boundaries

### ISSUE THREAD

**Issue by bsimyo** [NICTA/nationalmap#78]
Currently we support region coding with ABS approximations.  Some users need the actual AEC electoral boundaries.  Available at http://www.aec.gov.au/Electorates/gis/ .  Copyright and licence text that needs to be displayed is at
 http://www.aec.gov.au/Electorates/gis/GIS_Data_Download_Data_Licence.htm

**Comment by kring** [comment]
@kgrochow this is done right?

**Comment by kgrochow** [comment]
It is done.
